name: Manual Convert Surge List to Clash Ruleset

on:
  workflow_dispatch:  # 允许手动触发 GitHub Actions

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pyyaml

      - name: Convert .list to Clash Ruleset
        run: |
          cd Clash  # 进入 Clash 目录
          python convert.py  # 运行转换脚本

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Clash/clash_rules/
          git commit -m "Converted Surge .list to Clash ruleset" || echo "No changes to commit"
          git push
